### ISSUE TITLE
upper bound

### ISSUE THREAD

**Issue by WAAutomation** [saltoricristiano/cosmix-uda#10]
Thank you for your brilliant work, I want to know the upper bound of your UDA method, in other words, what are the results of fully supervised method on KITTI.

**Comment by saltoricristiano** [comment]
Hi @WAAutomation!

thx for your interest in our work!
We did not report the target upper bounds in our paper. 
However, since we don't have any class mapping, you can consider the performance of Minkowski Unet 32C on SemanticKITTI as the upperbound (should be something around 44 mIoU).

Let me know if I solved your doubts!
@saltoricristiano

**Comment by WAAutomation** [comment]
by using your code, my best result is 45 mIoU, but most paper reported are about 61 mIoU, I'm a little confused and want to know what went wrong.

**Comment by saltoricristiano** [comment]
Depends which Minkowski network they did use. In our case we took the unet 32C. Do you know which model did they use in the paper u found?

**Comment by WAAutomation** [comment]
https://github.com/mit-han-lab/spvnas
In this repo, there's a chart shows the mIoU of different version of the minkunet,  I don't know which one corresponds to your version, but the worst performance here is 58.9. And there's a version has 21.7M parameters which is the same as yours.

**Comment by saltoricristiano** [comment]
I quickly checked the model u sent but actually there are small differences such as the initial kernel size [here](https://github.com/mit-han-lab/spvnas/blob/69750e900d8687ac9fcc8e042b171cd1f6beffa1/core/models/semantic_kitti/minkunet.py#L89). We did not try to improve results in the supervised settings, therefore there may be further tunings/tricks to be done in order to improve the performance (e.g. different lr scheduler, augmentations, more epochs, different voxel size, warmup, and so on).

**Comment by WAAutomation** [comment]
thank you very much for your prompt reply. All doubts are solved

**Comment by yuan-zm** [comment]
> Depends which Minkowski network they did use. In our case we took the unet 32C. Do you know which model did they use in the paper u found?

Hi, @saltoricristiano,

According to your code, I find your backbone network is MinkUnet34, not 32C. And there is no 32C in MinkowskiEngine resp.

https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/minkunet.py
