### ISSUE TITLE
how to generate dataset weights?

### ISSUE THREAD

**Issue by sunnyHelen** [saltoricristiano/cosmix-uda#16]
Hi, thanks a lot for sharing your great work. I'm going to use the architecture but different datasets. So how should I generate the corresponding dataset weights file like "synlidar2semantickitti.npy"?

**Comment by saltoricristiano** [comment]
Hi @sunnyHelen,

I'm aswering you via email, I'm going to close this issue!

**Comment by laura-jehn** [comment]
Hello, I have the same question :) I am also trying to make cosmix work for my custom dataset. For now, I am using the synlidar2semantickitti.npy weights for my dataset also but the results are really bad. I don't know if the weights are the problem though, since even pretraining on semantickitti gives bad results. (I am trying to transfer from semantickitti to a custom dataset)
