### ISSUE TITLE
About the dataset used in paper 

### ISSUE THREAD

**Issue by yuan-zm** [saltoricristiano/cosmix-uda#8]
Hi, @saltoricristiano ,

Thank you for your brilliant work.

I want to know which dataset was used in your paper. As far as I know, the dataset used in "Transfer Learning from Synthetic to Real LiDAR Point Cloud for Semantic Segmentation" is the subdataset of SynLiDAR. To fairly compare with your method, I want to know which dataset you used in your paper, FullDataset or SubDataset?

**Comment by saltoricristiano** [comment]
Hi @dream-toy,

Thanks for your interest in our work!
For a fair comparison we used the same settings of the main SynLidar paper. So their same subset. If you check on their repo they now released also the subset.

Let me know if I fully solved your doubts!
Cheers,
Cristiano

**Comment by yuan-zm** [comment]
Thank you.  I will contact you if have any other questions.

**Comment by yuan-zm** [comment]
Hi @saltoricristiano,

The pkl files you provided in utils/datasets/_splits is not the SubDataset. 

![image](https://user-images.githubusercontent.com/28805336/198013700-5e92d5d0-f688-4159-9989-334853ef21b0.png)

For example, 249 is not in 00.zip.

**Comment by saltoricristiano** [comment]
Hi @dream-toy, 

at experimental and writing time, the SynLiDAR sub-split was not available. Based on authors feedback we uniformly sampled 1/10 of the data for each sequence. However now they published the original split used in their paper and it's a bit different from ours.

I guess you won't experience a big difference in the results as in the end both our and their sampling are performed uniformly in each sequence and the frame rate is quite high meaning that the different scenarios should be covered and sampled pretty well in both the splits.
If you want to compare the results with ours, I invite you to use our provided splits in order to be in the same settings.

Feel free to contact me for any other doubt!
Cheers, 
saltoricristiano
